### ISSUE TITLE
Can't load hyper-spotify

### ISSUE THREAD

**Issue by sinewave440hz** [panz3r/hyper-spotify#1]
Just installed this and got the following error: 

```
bundle.js:1 Error: Cannot find module '/Users/sinewave/.hyper_plugins/node_modules/hyper-spotify'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at le.plugins.concat.map.ce (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8876)
    at Array.map (native)
    at se (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8830)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:10365)
    at __webpack_require__ (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:368728)
```

Any idea what might be causing this? Currently on node 7.3 in nvm with hyper plugins hyperpower and hyperline installed, if that helps...

**Comment by panz3r** [comment]
Hi @sinewave440hz,
Sorry to hear you are encountering this issue.
Unfortunately this seems to be a common issue with Hyper plugins (see here https://github.com/zeit/hyper/issues/191);

I had the same issue on a fresh Hyper installation and after reloading and restarting it,
the issue was gone.

If restarting Hyper doesn't fix your issue, try running the following command (as suggested on the Hyper issue linked above)
```bash
cd ~/.hyper_plugins && npm install
```

Let me know if this fixes your issue so that I can consider adding it to the README of hyper-spotify

**Comment by panz3r** [comment]
Added `Troubleshooting` section to `README` to outline possible solutions (commit https://github.com/panz3r/hyper-spotify/commit/d94f1c9c6794c21a86de91b5987b247e86c9fda2)

**Comment by fuzzy76** [comment]
Isn't that a workaround and not a fix? I'm seeing this on every single plugin using hyper 1.3.3 on macOS  10.12.5.

**Comment by sinewave440hz** [comment]
@panz3r Thank you, yes, that solved the issue for me! Nice.

**Comment by panz3r** [comment]
@sinewave440hz Glad to hear that, thank you for your patience and I hope you enjoy this plugin.

@fuzzy76 You can find further details about the issue here https://github.com/zeit/hyper/issues/191
