### ISSUE TITLE
Spotifyfooter over content & split line thought itself

### ISSUE THREAD

**Issue by IanCStewart** [panz3r/hyper-spotify#12]
Content reaches under spotifyfooter. Expect content to stop at footer.
![screen shot 2017-09-21 at 23 12 50](https://user-images.githubusercontent.com/14125280/30719194-d8d2f928-9f22-11e7-9303-da3453797643.png)

Split line goes over spotifyfooter. Expect the line to stop at footer.
<img width="217" alt="screen shot 2017-09-21 at 23 14 50" src="https://user-images.githubusercontent.com/14125280/30719195-d8d5047a-9f22-11e7-81ad-8d63a0bc0a70.png">

**Comment by jwhitmarsh** [comment]
@IanCStewart as a quick fix, I used the fix from https://github.com/panz3r/hyper-spotify/issues/4 and set padding as `0px 0px 28px` and that does the trick... for now.

**Comment by IanCStewart** [comment]
@jwhitmarsh especially the `for now` part is nice 😝. The best fix would be to make sure it gets injected as a real footer... see image below.

<img width="912" alt="screen shot 2017-09-26 at 10 23 38" src="https://user-images.githubusercontent.com/14125280/30850604-47782e30-a2a6-11e7-9179-7a89a9ad2747.png">

**Comment by panz3r** [comment]
Hi @IanCStewart , 

Thanks for your feedback, I'll try to find a solution to this issue as well as to issue #4, since they are closely related.

Unfortunately Hyper does not provide a simple way to insert a Footer (There's a bug related to this on Hyper itself [Hyper #379](https://github.com/zeit/hyper/issues/379)).

When I started `hyper-spotify`, I tried to make it compatible with [`hyper-statusline`](https://github.com/henrikdahl/hyper-statusline) but had a really hard time doing it (see this issue [hyper-statusline #44](https://github.com/henrikdahl/hyper-statusline/issues/44)) so I ended up doing a kind of a workaround attaching my plugin to the term part of Hyper. 
Since the PR I made to `hyper-statusline` has been merged, I need to rework part of the layout of `hyper-spotify` to solve this issue.

I'll try to do this as soon as possible since this has become a major problem.

**Comment by panz3r** [comment]
Hi @IanCStewart 
I just released a version of `hyper-spotify` containing a fix for this issue.

If you'd like to give it a try, you should be able to install it
- by running (if you're using [hpm](https://github.com/zeit/hpm)) 
```bash
$ hpm install hyper-spotify@next
```
- or by adding the version `#2.2.0` inside `~/.hyper.js` like this
```js
module.exports = {
  ...
  plugins: ['hyper-spotify#2.2.0']
  ...
}
```

Please let me know if it works as you expected

**Comment by IanCStewart** [comment]
Not sure what happened but i'm not really able to test it 😅.

```
bundle.js:1 [Notification] Plugin error: hyper-spotify: Error occurred in `mapHyperState`. Check Developer Tools for details.
/Users/ian/.hyper_plugins/node_modules/hyper-spotify/dist/index.js:107 Uncaught TypeError: Cannot read property 'position' of undefined
    at _class.render (/Users/ian/.hyper_plugins/node_modules/hyper-spotify/dist/index.js:107)
    at c._renderValidatedComponentWithoutOwnerOrContext (bundle.js:4)
    at c._renderValidatedComponent (bundle.js:4)
    at c.performInitialMount (bundle.js:4)
    at c.mountComponent (bundle.js:4)
    at Object.mountComponent (bundle.js:1)
    at c.performInitialMount (bundle.js:4)
    at c.mountComponent (bundle.js:4)
    at Object.mountComponent (bundle.js:1)
    at c.performInitialMount (bundle.js:4)
```

**Comment by panz3r** [comment]
@IanCStewart 
Sorry, my fault.

Can you try with version `2.2.1`, this should fix your latest issue

**Comment by IanCStewart** [comment]
Might be me but it doesn't seem to change much.

<img width="308" alt="screen shot 2017-09-28 at 13 34 31" src="https://user-images.githubusercontent.com/14125280/30964538-0a46a520-a452-11e7-8dea-4ec2a56abe3d.png">

```❯ hpm ls
hyper-snazzy
hypercwd
hyper-spotify#2.2.1
hypernpm```

**Comment by panz3r** [comment]
Hi @IanCStewart ,

That's strange.
I just publish a new version `2.2.2`, could you please test this out.

You should also verify that Hyper is loading the right version, to do so open `Developer Tools` and check if you see this line
```Plugin hyper-spotify (2.2.2) loaded.```

If the version is not matching try a `Full Reload` and check again.

Thanks for your collaboration.

**Comment by IanCStewart** [comment]
I'm guessing the last time it didn't reload correctly. Still getting this error though (`mapHyperState`).

```
bundle.js:1 TypeError: Cannot read property 'position' of undefined
    at mapHyperState (/Users/ian/.hyper_plugins/node_modules/hyper-spotify/dist/index.js:66:30)
    at C.(anonymous function).state.forEach (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:6713)
    at Array.forEach (native)
    at Function.Object [as mapToProps] (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:6687)
    at n (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:74499)
    at Function.n.mapToProps (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:74636)
    at n (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:74481)
    at handleFirstCall (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:52983)
    at file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:53625
bundle.js:1 [Notification] Plugin error: hyper-spotify: Error occurred in `mapHyperState`. Check Developer Tools for details.
/Users/ian/.hyper_plugins/node_modules/hyper-spotify/dist/index.js:107 Uncaught TypeError: Cannot read property 'position' of undefined
    at _class.render (/Users/ian/.hyper_plugins/node_modules/hyper-spotify/dist/index.js:107)
    at c._renderValidatedComponentWithoutOwnerOrContext (bundle.js:4)
    at c._renderValidatedComponent (bundle.js:4)
    at c.performInitialMount (bundle.js:4)
    at c.mountComponent (bundle.js:4)
    at Object.mountComponent (bundle.js:1)
    at c.performInitialMount (bundle.js:4)
    at c.mountComponent (bundle.js:4)
    at Object.mountComponent (bundle.js:1)
    at c.performInitialMount (bundle.js:4)
```

And as requested it was loaded:
```
(re)loading renderer plugins
bundle.js:1 Plugin hyper-snazzy (1.2.2) loaded.
bundle.js:1 Plugin hypercwd (1.1.1) loaded.
bundle.js:1 Plugin hyper-spotify (2.2.2) loaded.
bundle.js:1 Plugin hypernpm (0.1.1) loaded.
```

**Comment by panz3r** [comment]
Hi @IanCStewart ,

New version `2.2.4` just released.

Once again thanks for your patience and your collaboration.

Regarding `hpm` I think it cannot load packages tags (such as `next`), I should drop that suggestion in this cases.

**Comment by IanCStewart** [comment]
Yes now we're getting somewhere. The only thing is my font got lost in translation this time.

<img width="374" alt="screen shot 2017-09-29 at 09 32 32" src="https://user-images.githubusercontent.com/14125280/31005476-2353382e-a4f9-11e7-8d95-be0c06d03f76.png">
